### ISSUE TITLE
Show standard output

### ISSUE THREAD

**Issue by balping** [bitsandsalsa/lxd_gui_container#1]
Hi,

How can I view what an attached process is writing to the standard output?

Eg. `./attach_app.sh container "glxinfo"` -> I would like to see the output of `glxinfo`.

**Comment by bitsandsalsa** [comment]
`glxinfo` is a commandline tool so it does not draw a graphical window and therefore there is nothing to "attach" to. I think your best bet is to install a terminal emulator in your container and run your commandline tools in there.

From host, install terminal emulator (e.g, xterm, gnome-terminal) in container:
`lxc exec your-container apt install xterm`

Now, attach to the terminal emulator window:
`attach_app.sh your-container xterm`

**Comment by balping** [comment]
Hi,

`glxinfo` was just an example, but other programs weren't showing their output either. Thanks for the workaround.
